### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by emanueljoivo** [OpenEnade/ClientApp#10]
Implement an about page like the example below. Note that, following the directory structure set as the default for the application, the ideal folder for placing this .vue file is in src/views
![aboutpage](https://user-images.githubusercontent.com/20460600/46973159-c6931580-d096-11e8-8412-e8d9ec833ca6.png)

**Comment by paulofelipefeitosa** [comment]
@OpenEnade/projeto-novo looks great!!! Thank you :heart_eyes:

**Comment by emanueljoivo** [comment]
Missing set styles of this view.
