### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by emanueljoivo** [OpenEnade/ClientApp#11]
Implement a contact page like the example below. Note that, following the directory structure set as the default for the application, the ideal folder for placing this .vue file is in src/views
![contactpage](https://user-images.githubusercontent.com/20460600/46974686-1d9ae980-d09b-11e8-9797-80a4f75837a1.png)

**Comment by paulofelipefeitosa** [comment]
@OpenEnade/projeto-novo looks great!!! Thank you for your hard work :smile: !!
